python GetOldTweets3.py --querysearch "💔" --lang en --maxtweets 2000 --output 💔.csv
python GetOldTweets3.py --querysearch "💋" --lang en --maxtweets 2000 --output 💋.csv
python GetOldTweets3.py --querysearch "💖" --lang en --maxtweets 2000 --output 💖.csv
python GetOldTweets3.py --querysearch "❤" --lang en --maxtweets 2000 --output ❤.csv
python GetOldTweets3.py --querysearch "😍" --lang en --maxtweets 2000 --output 😍.csv
python GetOldTweets3.py --querysearch "😘" --lang en --maxtweets 2000 --output 😘.csv
python GetOldTweets3.py --querysearch "😚" --lang en --maxtweets 2000 --output 😚.csv
python GetOldTweets3.py --querysearch "🤩" --lang en --maxtweets 2000 --output 🤩.csv
python GetOldTweets3.py --querysearch "😱" --lang en --maxtweets 2000 --output 😱.csv
python GetOldTweets3.py --querysearch "😖" --lang en --maxtweets 2000 --output 😖.csv
python GetOldTweets3.py --querysearch "😣" --lang en --maxtweets 2000 --output 😣.csv
python GetOldTweets3.py --querysearch "😩" --lang en --maxtweets 2000 --output 😩.csv
python GetOldTweets3.py --querysearch "😫" --lang en --maxtweets 2000 --output 😫.csv
python GetOldTweets3.py --querysearch "😳" --lang en --maxtweets 2000 --output 😳.csv
python GetOldTweets3.py --querysearch "😕" --lang en --maxtweets 2000 --output 😕.csv
python GetOldTweets3.py --querysearch "😞" --lang en --maxtweets 2000 --output 😞.csv
python GetOldTweets3.py --querysearch "😓" --lang en --maxtweets 2000 --output 😓.csv
python GetOldTweets3.py --querysearch "😥" --lang en --maxtweets 2000 --output 😥.csv
python GetOldTweets3.py --querysearch "😢" --lang en --maxtweets 2000 --output 😢.csv
python GetOldTweets3.py --querysearch "😭" --lang en --maxtweets 2000 --output 😭.csv
python GetOldTweets3.py --querysearch "😮" --lang en --maxtweets 2000 --output 😮.csv
python GetOldTweets3.py --querysearch "😲" --lang en --maxtweets 2000 --output 😲.csv
python GetOldTweets3.py --querysearch "😤" --lang en --maxtweets 2000 --output 😤.csv
python GetOldTweets3.py --querysearch "😡" --lang en --maxtweets 2000 --output 😡.csv
python GetOldTweets3.py --querysearch "😠" --lang en --maxtweets 2000 --output 😠.csv
python GetOldTweets3.py --querysearch "😏" --lang en --maxtweets 2000 --output 😏.csv
python GetOldTweets3.py --querysearch "😬" --lang en --maxtweets 2000 --output 😬.csv
python GetOldTweets3.py --querysearch "😒" --lang en --maxtweets 2000 --output 😒.csv
python GetOldTweets3.py --querysearch "😌" --lang en --maxtweets 2000 --output 😌.csv
python GetOldTweets3.py --querysearch "😔" --lang en --maxtweets 2000 --output 😔.csv
python GetOldTweets3.py --querysearch "😴" --lang en --maxtweets 2000 --output 😴.csv
python GetOldTweets3.py --querysearch "😅" --lang en --maxtweets 2000 --output 😅.csv
python GetOldTweets3.py --querysearch "😄" --lang en --maxtweets 2000 --output 😄.csv
python GetOldTweets3.py --querysearch "😂" --lang en --maxtweets 2000 --output 😂.csv
python GetOldTweets3.py --querysearch "😊" --lang en --maxtweets 2000 --output 😊.csv
python GetOldTweets3.py --querysearch "😉" --lang en --maxtweets 2000 --output 😉.csv
python GetOldTweets3.py --querysearch "😋" --lang en --maxtweets 2000 --output 😋.csv
python GetOldTweets3.py --querysearch "😜" --lang en --maxtweets 2000 --output 😜.csv
python GetOldTweets3.py --querysearch "😛" --lang en --maxtweets 2000 --output 😛.csv
python GetOldTweets3.py --querysearch "😝" --lang en --maxtweets 2000 --output 😝.csv
python GetOldTweets3.py --querysearch "🤢" --lang en --maxtweets 2000 --output 🤢.csv
python GetOldTweets3.py --querysearch "🤮" --lang en --maxtweets 2000 --output 🤮.csv
python GetOldTweets3.py --querysearch "😷" --lang en --maxtweets 2000 --output 😷.csv
python GetOldTweets3.py --querysearch "😵" --lang en --maxtweets 2000 --output 😵.csv
python GetOldTweets3.py --querysearch "👌" --lang en --maxtweets 2000 --output 👌.csv
python GetOldTweets3.py --querysearch "👍" --lang en --maxtweets 2000 --output 👍.csv
python GetOldTweets3.py --querysearch "👏" --lang en --maxtweets 2000 --output 👏.csv
python GetOldTweets3.py --querysearch "🙌" --lang en --maxtweets 2000 --output 🙌.csv
python GetOldTweets3.py --querysearch "🙏" --lang en --maxtweets 2000 --output 🙏.csv
python GetOldTweets3.py --querysearch "✌" --lang en --maxtweets 2000 --output ✌.csv
python GetOldTweets3.py --querysearch "😎" --lang en --maxtweets 2000 --output 😎.csv
python GetOldTweets3.py --querysearch "☺" --lang en --maxtweets 2000 --output ☺.csv
python GetOldTweets3.py --querysearch "🙈" --lang en --maxtweets 2000 --output 🙈.csv
python GetOldTweets3.py --querysearch "🙊" --lang en --maxtweets 2000 --output 🙊.csv
python GetOldTweets3.py --querysearch "🔥" --lang en --maxtweets 2000 --output 🔥.csv
python GetOldTweets3.py --querysearch "💯" --lang en --maxtweets 2000 --output 💯.csv
python GetOldTweets3.py --querysearch "🎉" --lang en --maxtweets 2000 --output 🎉.csv
